### ISSUE TITLE
Create a proper documentation

### ISSUE THREAD

**Issue by srevinsaju** [srevinsaju/guiscrcpy#60]

**Comment by tukusejssirs** [comment]
#### Tasks

Add notes on
- [ ] how to build the program for current user;
- [ ] how to build the program system-wide;
- [ ] how to install fonts (it should be done by the build script; see #63);

**Comment by tukusejssirs** [comment]
> As no action on the issue was taken, bot closes issue.

@srevinsaju, I’ve just wanted to re-open this issue, but to my surprise it was _not_ actually closed by the @github-actions bot in contrary what it said. It might be a good idea to check why it failed to close this issue. :smiley:

**Comment by srevinsaju** [comment]
Maybe @github-actions wants to wait for a week before trying to close this issue @tukusejssirs 
It tried to close it 2-days ago, an issue / PR with the no-activity label

**Comment by srevinsaju** [comment]
@tukusejssirs Can you check the documentation is alright?
